# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stock-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for stock-iOS
  pod 'Toast-Swift', '~> 3.0.1'
  pod "SwiftSpinner"

  target 'stock-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'stock-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
